config/routes.rb
Rails.application.routes.draw do
  get 'portfolio/home'
  get 'portfolio/synth'
  get 'portfolio/vst'
  get 'portfolio/whizz'
  get 'portfolio/rewinder'
  get 'portfolio/modular'
  get 'portfolio/renderer'
  get 'portfolio/unity'
  get 'portfolio/udk'
  get 'portfolio/max7'
  get 'portfolio/download_synth'
  get 'portfolio/download_zip'
  root 'portfolio#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def home
  end

  def synth
  end

  def vst
  end

  def rewinder
  end
end

app/controllers/portfolio_controller.rb
class PortfolioController < ApplicationController
  def home
  end

  def synth
  end

  def vst
  end

  def rewinder
  end

  def whizz
  end

  def renderer
  end

  def modular
  end

  def unity
  end

  def udk
  end

  def max7
  end

  def download_zip
    send_file(
    "#{Rails.root}/public/Synth.zip",
    filename: "Synth.zip"
    )
  end

  def download_synth
    send_file(
    "#{Rails.root}/public/SynthesizerStandalone.exe",
    filename: "SynthesizerStandalone.exe"
    )
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/portfolio_helper.rb
module PortfolioHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Artur Jaakman</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" type="text/css" href="http://fonts.googleapis.com/css?family=Raleway">
  </head>

  <body>
    <div class = "container">
      <nav class="navbar navbar-default">
        <ul class="nav navbar-nav">
          <li><%= link_to "Home", root_path %></li>
          <li>
            <a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">Audio Programming</a>
            <ul class="dropdown-menu" aria-labelledby="dropdownMenuLink">
              <li><%= link_to "Modular Audio App", portfolio_modular_path %></li>
              <li><%= link_to "Audio Synthesizer", portfolio_synth_path %></li>
              <li><%= link_to "Distortion VST Plugin", portfolio_vst_path %></li>
              <li><%= link_to "Max7 Synthesizer", portfolio_max7_path %></li>
            </ul>
          </li>
          <li>
            <a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">Games and Audio</a>
            <ul class="dropdown-menu" aria-labelledby="dropdownMenuLink">
              <li><%= link_to "3D Renderer", portfolio_renderer_path %></li>
              <li><%= link_to "UE4 Bullet Whizz", portfolio_whizz_path %></li>
              <li><%= link_to "UE4 Rewinder Class", portfolio_rewinder_path %></li>
              <li><%= link_to "Unity Simple Game", portfolio_unity_path %></li>
              <li><%= link_to "UDK Sound Design", portfolio_udk_path %></li>
            </ul>
          </li>
        </ul>
      </nav>
      <%= yield %>
    </div>
  </body>
</html>

app/views/portfolio/home.html.erb
<h1><b>Artur Jaakman</b> </h1>
<h4>
  <b>Audio Programmer</b>
</h4>
<p>
  This website documents and showcases some of my work. <br>
  Scroll down to see summaries of my recent projects or browse the navbar above to see older work.
</p>
<p>
  Email: <b> artur.jaakman@gmail.com </b><br>
  Github: <a href="https://github.com/ajaakman">github.com/ajaakman</a>
</p><p>
  <b>Education:</b> <br>
  Information Technology (MSc). University of Aberdeen. <br>
  Audio Technology (BSc Hons). Glasgow Caledonian University.
</p>
<h2> My Projects: </h2>

<h3> Audio Synthesizer </h3>
<p> A 32bit Windows app made with WaveOut API. The UI is made with C# WPF.
The WPF window also hosts a C++ Win32 API window that draws the piano keys using Direct2D. </p>
<b> More info: </b> <%= link_to "Audio Synthesizer", portfolio_synth_path %> <br>
<iframe class="embed-responsive-item" src="https://www.youtube.com/embed/IEx4dplyGIs?enablejsapi=1&amp;autoplay=0" height=450 width=800 allowfullscreen=""></iframe> <br>

<h3> Modular Audio App </h3>
<p> A modular audio synthesis app with a C++ backend compiled to WebAssembly using Emscripten and React.js frontend UI. </p>
<b> More info: </b> <%= link_to "Modular Audio App", portfolio_modular_path %> <br>
<iframe class="embed-responsive-item" src="https://www.youtube.com/embed/7i614y3Gg3U?enablejsapi=1&amp;autoplay=0" height=450 width=800 allowfullscreen=""></iframe> <br>

<h3> 3D Renderer </h3>
<p> A simple renderer with 3d audio support made with C++, OpenGL and OpenAL. Compiled to WebGL using Emscripten. </p>
<b> More info: </b> <%= link_to "3D Renderer", portfolio_renderer_path %> <br>
<iframe class="embed-responsive-item" src="https://www.youtube.com/embed/291APD3EANM?enablejsapi=1&amp;autoplay=0" height=450 width=800 allowfullscreen=""></iframe> <br>

<br>
<br>

app/views/portfolio/max7.html.erb
<h1>Max7 Monophonic Synthesizer</h1>
<p>A modular monophonic synth made in Max7. One of my first audio programming projects made in 2015 for Audio Processing and Effects module at Glasgow Caledonian University. </p>
<div class="iframe-container">
  <iframe class="embed-responsive-item" src="https://www.youtube.com/embed/tLJQgmarUIE?enablejsapi=1&amp;autoplay=0" allowfullscreen=""></iframe>
</div>
<br>
<br>

app/views/portfolio/modular.html.erb
<h1>Modular Audio App</h1>
<p>This project uses a C++ audio library witten from scratch and compiled to WebAssembly using Emscripten.
A browser based UI was made using React.js to create MaxMSP/PureData-like crossplatform modular audio app.
The audio library was written using object oriented design with the idea of having modular 'Audio Components'
that could be connected to each other to form a signal chain in a user defined configuration. Currently two components
have been added: the Oscillator and the LowPass Filter. The framework is fully in place to add more components
rapidly, including Python Scripts to genereate boilerplate code. More technical info can be found in the github repo
ReadMe files.</p>
<p><b>TODO: </b> Add more components: Filters, Distortion Effects, Delay, Reverb, Audio File Player, etc. <br>
&nbsp &nbsp &nbsp &nbsp &nbsp &nbsp Add small screen and touch support.</p>
<p><b>Audio Source Code: </b><a href="https://github.com/ajaakman/cpp-audio-library">https://github.com/ajaakman/cpp-audio-library</a><br></p>
<p><b>UI Source Code: </b><a href="https://github.com/ajaakman/react-audio-app">https://github.com/ajaakman/react-audio-app</a><br></p>
<p><b>Try Online: </b><a href="http://audio.arturjaakman.com">audio.arturjaakman.com</a><br></p>
<div class="iframe-container">
  <iframe class="embed-responsive-item" src="https://www.youtube.com/embed/7i614y3Gg3U?enablejsapi=1&amp;autoplay=0" allowfullscreen=""></iframe>
</div>
<br>
<br>

app/views/portfolio/renderer.html.erb
<h1>3D OpenGL Renderer</h1>
<p>A 3D renderer made with C++ and OpenGL. Positional audio support using OpenAL. Can be compiled to WebAssembly via Emscripten to run in the browser.</p>
<p><b>Source Code: </b><a href="https://github.com/ajaakman/3d-renderer">https://github.com/ajaakman/3d-renderer</a><br></p>
<p><b>Try Online: </b><a href="http://renderer.arturjaakman.com">http://renderer.arturjaakman.com</a><br></p>
<div class="iframe-container">
  <iframe class="embed-responsive-item" src="https://www.youtube.com/embed/291APD3EANM?enablejsapi=1&amp;autoplay=0" allowfullscreen=""></iframe>
</div>
<br>
<br>

app/views/portfolio/rewinder.html.erb
<h1>UE4 Rewinder Component Class</h1>
<p>A UE component class that can be attached to any UE4 actor and will track its position for the last <i>n</i> number of cycles. When activated it returns the actor to its
location at the previous cycle, also setting the velocity and torque, until deactivated or until the tracking array runs out of recorded cycles.</p>
<p><b>Source Code: </b><a href="https://github.com/ajaakman/UE4-roller-game">https://github.com/ajaakman/UE4-roller-game</a><br></p>
<div class="iframe-container">
  <iframe class="embed-responsive-item" src="https://www.youtube.com/embed/6nDcNYWrLKE?enablejsapi=1&amp;autoplay=0" allowfullscreen=""></iframe>
</div>
<br>
<br>

app/views/portfolio/synth.html.erb
<h1>Audio Synthesizer</h1>
<p>A Windows app that can be played using the keyboard, mouse or MIDI keyboard.</p>
<p>This project was originally a simple C++ audio synthesizer made using the waveOut API. I then added a native Windows GUI interface rendered using Direct2D.
I was then curious to see if a WPF Interface could be added to control the synth parameters. The Keyboard on the top right is the original Win32 API window, using
Direct2D to render the keys, hosted in a WPF Window.</p>

<p><b>TODO: </b> Add more effects: filters, reverb, delay, etc.<br>
&nbsp &nbsp &nbsp &nbsp &nbsp &nbsp Improve Midi support. (Keyboard needs to be plugged in on startup, Midi messages aren't correct and don't work properly on some keyboards)</p>
<p><b>Source Code: </b><a href="https://github.com/ajaakman/sound-synthesizer">https://github.com/ajaakman/sound-synthesizer</a><br>
  <b>Downoad: </b><%= link_to 'Windows 32bit', portfolio_download_zip_url %><br>
</p>
<div class="iframe-container">
  <iframe class="embed-responsive-item" src="https://www.youtube.com/embed/IEx4dplyGIs?enablejsapi=1&amp;autoplay=0" allowfullscreen=""></iframe>
</div>
<br>
<p>Below is the original app that ran in a standalone Win32 API Window and didn't have the WPF Controls.</p>
<b>Downoad Win32 Standalone: </b><%= link_to 'Windows 32bit', portfolio_download_synth_url %><br>
<div class="iframe-container">
  <iframe class="embed-responsive-item" src="https://www.youtube.com/embed/UtaG3e2Mg_A?enablejsapi=1&amp;autoplay=0" allowfullscreen=""></iframe>
</div>
<br>
<p>I also experimented in trying to get the synth to work on mobile devices using the SDL2 library.</p>
<p><b>Source Code: </b><a href="https://github.com/ajaakman/SDLFramework">https://github.com/ajaakman/SDLFramework</a><br>
<div class="iframe-container">
  <iframe class="embed-responsive-item" src="https://www.youtube.com/embed/DUm2JnuyWnI?enablejsapi=1&amp;autoplay=0" allowfullscreen=""></iframe>
</div>
<br>
<br>

app/views/portfolio/udk.html.erb
<h1>UDK Game Audio</h1>
<p>My first introduction to game audio design from 2015. Made for Games Sound Design module at Glasgow Caledonian University.
The assignment was to populate a map in UDK with recorded sound effects and effects from free libraries. Additionally the project had some
effects generated in real time by having UDK communicate with Max7 via OSC (Open Sound Control) and have the Max Patch generate the sound effect.</p>
<div class="iframe-container">
  <iframe class="embed-responsive-item" src="https://www.youtube.com/embed/TfZ5xRJK3kU?enablejsapi=1&amp;autoplay=0" allowfullscreen=""></iframe>
</div>
<br>
<br>

app/views/portfolio/unity.html.erb
<h1>Unity Game</h1>
<p>One of my first coding and Unity game engine projects. Made in 2016 for Games Audio module at Glasgow Caledonian University.
The assignment was to make a game with sound effects using FMOD.
<br>
I wanted to make the simplest game I could think of with a Win and Lose condition.
In this case, survive long enough to win, if the dinosaur catches you, you lose.
<br>
The dinosaur will rotate and charge towards the player and the player will have
to dodge it. As time passes the dinosaurs charge becomes faster.
<br>
Most sound effects are foley recording or from freesound.org. The day and night cycle triggers different
background noise. During the night the player will hear crickets, while during the day the player will hear bird chirping.
Additinally, the player also hears a hearbeat
that gets quicker the more you move and slows down when you stop and rest.</p>
<div class="iframe-container">
  <iframe class="embed-responsive-item" src="https://www.youtube.com/embed/iNJDTGtYeLA?enablejsapi=1&amp;autoplay=0" allowfullscreen=""></iframe>
</div>
<br>
<br>

app/views/portfolio/vst.html.erb
<h1>Distortion VST Plugin</h1>
<p>One of my first C++ projects made in 2017 for Advanced Audio Processing and Effects module at Glasgow Caledonian University. A VST plugin made using the JUCE C++ framework
that uses a simple arctan function to shape the sound. It can apply the effect to one channel or two channels separately creating an interesting stereo effect.</p>
<p><b>TODO: </b>Make the distortion have a non-linear response. i.e. The lowder the sound the more distortion. <br>
&nbsp &nbsp &nbsp &nbsp &nbsp &nbsp Add visual effects to show the amount of distortion applied and which channel is currenly active. </p>
<p><b>Source Code: </b><a href="https://github.com/ajaakman/DistortionVSTPlugin">https://github.com/ajaakman/DistortionVSTPlugin</a><br>
<div class="iframe-container">
  <iframe class="embed-responsive-item" src="https://www.youtube.com/embed/_exlC5PFn08?enablejsapi=1&amp;autoplay=0" allowfullscreen=""></iframe>
</div>

<br>
<br>

app/views/portfolio/whizz.html.erb
<h1>UE4 Bullet Whizz</h1>
<p>A bullet whizz sound effect made in UE4 using Blueprints.

</p>
<div class="iframe-container">
  <iframe class="embed-responsive-item" src="https://www.youtube.com/embed/TGedLVXWh9w?enablejsapi=1&amp;autoplay=0" allowfullscreen=""></iframe>
</div>

<br>
<h4>UE4 BLUEPRINT:</h4>
<%= image_tag("BulletWhizz.PNG") %>
<br>
<br>